### ISSUE TITLE
Provide working example

### ISSUE THREAD

**Issue by tomasgreif** [jstephenj14/Monotonic-WOE-Binning-Algorithm#1]
Can you provide example how the function is used? I am using newer version of pandas and getting error in the aggregation. Apparently renaming was deprecated for the aggregations: https://github.com/pandas-dev/pandas/issues/18366

**Comment by nova0816** [comment]
I'd like to echo this.  I feed "Y" and "dataset" with various data types but get error each time.  Can you instruct how to use this?

**Comment by jstephenj14** [comment]
I apologize for answering after such a long time. I'm returning from a hiatus. I'll be fixing this shortly

**Comment by nova0816** [comment]
Thanks!

**Comment by jstephenj14** [comment]
A demo_run.py file has now been included in the tests/ directory. The function has now been modularized and packaged so the demo_run.py should help clarify things better now.
