### ISSUE TITLE
"defaults_threshold“ is not  defined

### ISSUE THREAD

**Issue by hjnhenry** [jstephenj14/Monotonic-WOE-Binning-Algorithm#2]
condition = (summary["nsamples"]<n_threshold)|(summary["nsamples_lead"]<n_threshold)|(summary["means"]*summary["nsamples"]<defaults_threshold)|(summary["means_lead"]*summary["nsamples_lead"]<defaults_threshold)

summary["p_value"] = summary.apply(lambda row: row["p_value"] + 1 if (row["nsamples"]<n_threshold)|(row["nsamples_lead"]<n_threshold)|(row["means"]*row["nsamples"]<defaults_threshold)|(row["means_lead"]*row["nsamples_lead"]<defaults_threshold)
                 else row["p_value"], axis = 1 )

**Comment by jstephenj14** [comment]
I apologize for answering after such a long time. I'm returning from a hiatus. I'll be fixing this shortly.

**Comment by jstephenj14** [comment]
This has now been defined.
