### ISSUE TITLE
defaults_threshold is not define and the df.groupby.agg is not available

### ISSUE THREAD

**Issue by chaoyue729** [jstephenj14/Monotonic-WOE-Binning-Algorithm#3]
defaults_threshold = xxx
    summary = sample_set.groupby([column]).agg(['mean','size','std'])
    
    summary.columns = summary.columns.droplevel(level=0)
    new_col = ["means","nsamples","std_dev"]
    
    summary = summary[["mean","size","std"]]
    summary.columns = new_col

**Comment by jstephenj14** [comment]
I apologize for answering after such a long time. I'm returning from a hiatus. I'll be fixing this shortly

**Comment by jstephenj14** [comment]
This has been corrected. defaults_threshold is now y_threshold
