### ISSUE TITLE
SpecificationError: cannot perform renaming for goodbad with a nested dictionary

### ISSUE THREAD

**Issue by transposition** [jstephenj14/Monotonic-WOE-Binning-Algorithm#4]
python3……

**Comment by tilii** [comment]
I get the same error with python2, and am pretty sure that this is related to latest version of pandas where the renaming has been removed.

@jstephenj14 Should we expect any fix for this?

**Comment by jstephenj14** [comment]
I apologize for answering after such a long time. I'm returning from a hiatus. I'll be fixing this shortly.

**Comment by jstephenj14** [comment]
The variable can now be named as per the dataset you're using.
