### ISSUE TITLE
Can you  provide a runable demo for your function？

### ISSUE THREAD

**Issue by Gpwner** [jstephenj14/Monotonic-WOE-Binning-Algorithm#5]
Sorry to asking,when I trying to run you function,but I  get so much problem.So can you provide a runable demo?Thanks in advance.

**Comment by theinexorable** [comment]
Yes, I still can't extract the entire logic behind this and the original code.

**Comment by jstephenj14** [comment]
I apologize for answering after such a long time. I'm returning from a hiatus. I'll be streamlining the code and providing a runable demo shortly.

**Comment by jstephenj14** [comment]
A demo_run.py file has been included under tests/ for your reference.
